### ISSUE TITLE
Issue USB loading with V386

### ISSUE THREAD

**Issue by bradkoro** [FIX94/Nintendont#202] opened 2016-02-09 21:46 UTC
Hello everyone, 

For some reason 386 isn't working for me, it fails to load my usb every time. any other version before that works no problem. Perhaps issue with coding on revision of 386. Please look into it.

Thanks.

**Comment by GB-CG** [comment] 2016-02-09 22:11
Have you tried using a SD card?

**Comment by GerbilSoft** [comment] 2016-02-09 22:13
Version 386 merged in my GPT changes, which should only make a difference if your hard drive has a GPT partition table. Previous versions of Nintendont only supported MBR.

If possible, can you dump the first 4096 bytes of your hard disk? (i.e. the master boot record)

**Comment by bradkoro** [comment] 2016-02-09 22:27
SD card is not an option as of now it is almost max and expensive to buy a larger card. Thats odd because my usb set up was already GPT. Are you saying try MBR?

**Comment by GerbilSoft** [comment] 2016-02-09 22:41
Your USB drive is set up as GPT? Then it shouldn't have been working at all with Nintendont prior to v386.

I suspect you have a "hybrid MBR", which could have worked with Nintendont v385 (because it simply ignored the GPT portion), but may be confusing the new GPT code. Can you dump the first few sectors using the above tools and post them? (If you're using Mac or Linux, you can use the 'dd' command instead.)

**Comment by bradkoro** [comment] 2016-02-09 22:55
I have a mac and it is set up as ms-dos fat 32 with GUID partition. ok ill check it out. thanks

**Comment by GerbilSoft** [comment] 2016-02-09 23:02
That definitely sounds like Hybrid MBR. If you can dump the first few sectors as a binary file and post them, I can add proper support for it.

How to dump the hybrid MBR: (reference: https://discussions.apple.com/thread/2194992?tstart=0 )
1. Connect the Wii HDD to your Mac.
2. Open a Terminal.
3. Run the command:
```
diskutil list
```
You'll see a list of attached disks named /dev/disk0, /dev/disk1, etc. One of these will be the Wii HDD. (If you're unsure, try running it with and without the HDD connected; you should be able to see a difference.)
4. Run the command:
```
sudo dd if=/dev/diskn bs=512 count=34 | gzip >MBR.bin.gz
```
Replace "diskn" with "disk0", "disk1", or similar, depending on the output of diskutil. (WARNING: Make sure you ONLY specify the /dev/diskn parameter as the value for 'if', i.e. input file.)

You will have a file MBR.bin.gz containing the first 34 sectors of the hard drive (assuming 512-byte sectors). Post that file here and I'll take a look at it.

**Comment by JBoughter** [comment] 2016-02-10 04:44
I'm having the same issue with my USB, but it doesn't even work on 3.385. I really don't know what the issue is. It'll load up Nintendont just fine, but running something like Melee or any of the games I have will just make the screen go blank with no response even after 5 minutes with no signal coming from my Wii. It's a 600gb drive that is formatted FAT32.

**Comment by bradkoro** [comment] 2016-02-10 22:52
Wow I have no clue as well. Respond with this question on my issues on the website.
________________________________

**Comment by JBoughter** [comment] 2016-02-13 23:57
USB does not work at all for me too, but even with previous versions. I have verified nearly all of the issues from the Nintendont thread that are required for compatibility are not present, except for the last one which I have no clue what to do to check that.

Please help.

**Comment by GerbilSoft** [comment] 2016-02-14 00:02
Can you try the version in my GPT fix branch:

**Comment by JBoughter** [comment] 2016-02-14 00:15
As odd as it is, I actually can't get my SD card to work either. I have another Wii, but Nintendont works just fine on there as an SD card, but I don't have another USB to test.

Weird..

**Comment by carnage702** [comment] 2016-02-19 21:34
seems its your wii issues not nintendont if one sd card works on a wii and not on another something is off maybe a bad isntall of an cios or something.

**Comment by JBoughter** [comment] 2016-02-19 21:53
I thought Nintendont didn't use any cios's? That should be irrelevant, unless it's the actual homebrew. DIOS MIOS and running Brawl/Project M in cfg works just fine.

**Comment by carnage702** [comment] 2016-02-19 21:57
nintendont doesnt use any cios but its affected by them if over ios 58, manny people have old cios over ios58 wich nintendont uses the original ios58 wich can mess up usb among other things, some custom homebrew channel themes also mess it up and such.

**Comment by bradkoro** [comment] 2016-02-25 02:19
Hello GerbilSoft sorry for the late reply as i was out of town. Thank you for trying to help here. Unfortunately the fix you posted still did not work and can confirm 387 is also not working.

**Comment by carnage702** [comment] 2016-02-25 07:22
are you using a wii or wiiu?

**Comment by bradkoro** [comment] 2016-02-25 14:29
My usb work perfect on 385, and I am on a wii. GerbilSoft thinks it has to do with my MAC OSX formatting.

**Comment by GerbilSoft** [comment] 2016-02-25 15:54
@bradkoro If you can dump the first 34 sectors of your HDD as I detailed in my previous comment, I can take a look and see what's tripping it up.

**Comment by GerbilSoft** [comment] 2016-03-09 18:38
@bradkoro Can you test the latest build from my gpt-support-v3 branch?

https://github.com/GerbilSoft/Nintendont/blob/gpt-support-v3/loader/loader.dol

This branch adds support for up to 128 GPT partitions. If there's several other partitions in the GPT before the GCN partition, then that might be throwing off the current build. (Again, in order to confirm this, I'd need a dump of the first 34 sectors of your HDD.)

**Comment by bradkoro** [comment] 2016-03-26 16:19
@GerbilSoft Sorry it did not work as well :(
[MBR.bin.gz](https://github.com/FIX94/Nintendont/files/190535/MBR.bin.gz)

**Comment by GerbilSoft** [comment] 2016-03-30 16:14
I'll try dd'ing that partition table to a test drive when I get home tonight.

Taking a quick look, the partition layout is as follows:

MBR entries:
* Partition 1: Type 0xEE (EFI protective partition), start = LBA 1, length = 409,639
* Partition 2: Type 0x0B (FAT32, CHS?), start = LBA 411,648, length = 124,618,752

The GPT code in Nintendont doesn't care about the EFI protective partition's size, just the fact that it exists. Its presence tells the partition parser to ignore the rest of the MBR partition table and start reading the GPT.

GPT entries:
* Partition 1: EFI System Partition, start = LBA 40, end = LBA 409,639
* Partition 2: Basic data partition, start = LBA 411,648, end = LBA 125,030,399

The GPT "looks" valid. If it works for me when I test it later, I'll throw together a "debug" version that prints debugging information to a file on the SD card.

**Comment by timofonic** [comment] 2016-03-31 03:52
Thanks for your effort! I'm switching all my HDDs to GPT, this will be greatly appreciated if achieved :D

**Comment by bradkoro** [comment] 2016-04-01 04:52
@GerbilSoft thanks again, much appreciated.

**Comment by bradkoro** [comment] 2016-04-07 17:25
@GerbilSoft Any updates?

**Comment by GerbilSoft** [comment] 2016-04-20 16:23
...and then it hits me.

"Partition 1: EFI System Partition, start = LBA 40, end = LBA 409,639"

EFI System Partition is FAT32. This causes Nintendont to try loading games from that partition, and it obviously doesn't find anything.

I'll add an exception to skip EFI System Partitions when searching for the game partition.

**Comment by bradkoro** [comment] 2016-04-25 16:45
Thanks so much!

**Comment by GerbilSoft** [comment] 2016-05-04 03:03
@bradkoro Can you test out the latest build from my gpt-support-v3 branch? This version should skip EFI System Partitions.

https://github.com/GerbilSoft/Nintendont/blob/gpt-support-v3/loader/loader.dol

FatFS is also rebased to R0.12p3, which has some bug fixes for various things. (It also adds support for exFAT, but I disabled it because libcustomfat [loader] doesn't support exFAT.)

**Comment by GerbilSoft** [comment] 2016-05-04 03:07
Whoops, missed the kernel component of this fix. Recompiled and pushed now.

**Comment by GerbilSoft** [comment] 2016-05-16 16:51
I've received confirmation on GBAtemp that this fixes devices with Hybrid MBR and an EFI system partition, so I'll send a pull request later tonight.

Other upcoming changes:
* Support for MBR logical partitions. libcustomfat supports it, but FatFS doesn't.
* Use FatFS for both the loader and kernel. There's apparently a library called LibELM somewhere that provides a devoptab interface to FatFS, but all of the downloads seem to be offline. I'll probably end up not using stdio at all, which will probably reduce the size of the loader somewhat.
* menuhax branch, with all sorts of menu optimziations and debugging information.

**Comment by bradkoro** [comment] 2016-06-13 02:47
@GerbilSoft Thanks again, I will test it out.

**Closed** 2016-06-20 18:06 UTC
