### ISSUE TITLE
Mario Party 4 Extra Room "Crash"

### ISSUE THREAD

**Issue by Maesejesus** [FIX94/Nintendont#437] opened 2017-07-22 19:34 UTC
Hi, first of all, thanks for your hard work, Nintendont is fantastic.

I want to report a problem that Nintendont has with Mario Party 4. 
This game several modes, and this issue happens in the one named "Extra Room". 
There are two sub-modes, choosing any of them, and after selecting characters, the game will enter a strange state where it seems to be frozen, but the music plays normally, and you can even exit Nintendont through the button combination on your GC controller.

I've used a clean, verified dump (made by myself) of the PAL version; I'm trying this on a Wii, with all the options of Nintendont disabled:

Cheats Off
Debugger Off
Memcard Emulation Off
Cheat Path Off
Force Widescreen Off
Force Progressive Off (Although I tried with it on too)
Auto Boot Off
Unlock Read Speed Off
OSReport Off
Drive Access LED Off
Log Off
MaxPads 4
Language Eng
Video Auto
Native Control Off
Video Width Auto
Screen Position 0
Patch Pal50 Off
TRI Arcade Mode Off
Wiimote CC Rumble Off
Skip IPL Off

Also I'm using Nintendont Version 4.437, from April 17, 2017 and loading the game through USB (Not SD Card, if that makes any difference).

**Comment by TwilightSlick** [comment] 2017-08-24 18:20
Confirmed on v4.448 using the NTSC-U version on an original Wii with no MCEmu and native control on (all other options besides Native Control are OFF). This happens when loading from ISO or from the original disc via Nintendont (the ISO is a clean, Redump verified 1.1 copy, same version as the disc. Have not tested 1.0 yet, will do so).

The extra room crash does not occur in MIOS, I didn't expect it to. Same as what OP posted, select an option in the Extra Room, pick a character, then graphics will freeze with music still playing. Hardware Reset button works as expected and the issue does not repeat after pressing the Reset button.

**Comment by bobvargas** [comment] 2017-08-26 09:51
The same issue also happed to me as well.

I used all the default settings and after selecting a character in the extra room it would crash. I hope this gets fixed in the next version of nintendont.

**Comment by carnage702** [comment] 2017-08-26 10:01
this is a confirmed bug , but only when fix94 fells like looking at hit it that it will be solved i guess, patient is the key.

**Comment by FIX94** [comment] 2017-08-31 02:30
Just checked it and that freeze makes no sense to me right now, there is no debug prints indicating any problem, no ARStartDMA happening and no disc read happening either, it seems to suddenly just stop in its logic for no obvious reason or directly observable cause so fixing this would potentially take me weeks  because I have no point on where to start looking so I dont know when I'll start looking at it deeper yet.

**Comment by SuperrSonic** [comment] 2017-11-27 01:15
I know how to fix it, I don't know exactly what causes the crash but it can be avoided when compiling nintendont. See attachment, it's the latest version but doesn't crash in Mario Party 4. It's the exact same code, it's just been compiled with devkitppc r27 and devkitarm r45.

Again I'm not 100% certain that's the solution, but it's definitely fixed here.
[loader.zip](https://github.com/FIX94/Nintendont/files/1504424/loader.zip)

**Comment by FIX94** [comment] 2017-11-27 04:55
I've been testing different versions of devkitppc and arm, and it appears the arm version does not matter, only the ppc version does, things seem to change from devkitppc r27 to r28 for some reason, I dont quite know why yet.

**Comment by FIX94** [comment] 2017-11-27 07:54
what I also noticed now is that when I compile it, it doesnt properly load either (not crashing but just displaying things wrong) and after resetting ingame it is fine, interestingly enough, even on the current versions of devkitppc, when you get ingame and do a reset the extra room loads perfectly fine afterwards, this leads me to believe mario party 4 does not properly initialize parts of memory it uses on boot which then leads to these issues.

**Comment by SuperrSonic** [comment] 2018-01-04 05:49
That workaround + using native controller reveals a different problem, memory card emulation stops working after resetting in a lot of games, including Mario Party 4, this did not happen in Wind Waker and Melee, but every other game I tested it would just say the device inserted is not recognized.

Using a real memory card works though.

**Closed** 2020-04-06 09:20 UTC
Labels: bug
