### ISSUE TITLE
vWii rumble not work

### ISSUE THREAD

**Issue by hitoshiarakawa** [FIX94/Nintendont#673] opened 2019-05-20 00:07 UTC
The vibration function does not work when using dualshock3 with vWii of wii u.
Dualshock3 vibrated when the same sd card was inserted into a normal wii.
The game used is starfox adventure.
Thank you.

**Comment by carnage702** [comment] 2019-05-20 06:01
wiiU has handicapped power supply from usb doors so im guessing that the dualshock3 doesnt rumble on vwii becuase is not getting enough power from usb doors from the wiiu itself.

**Comment by hitoshiarakawa** [comment] 2019-05-20 06:38
Oh I see. I will try using a self-powered USB hub later. Thank you.

**Comment by carnage702** [comment] 2019-05-20 16:13
nintendont is not too keen on usb hubs, they arent officialy supported, your best bet would be a y cable imo.

**Comment by hitoshiarakawa** [comment] 2019-05-22 12:47
Thank you for your reply. I bought a cheap y cable and tried it, but unfortunately it didn't vibrate. Is there anything else I can think of?

**Comment by carnage702** [comment] 2019-05-22 16:42
no idea, i only own 2 ps3 controllers wihch didnt rumble, the earlier ones so i cant do anything. make sure your version of nintendont is the same on both consoles i guess.

**Comment by Missingphy** [comment] 2019-06-16 03:18
so can non-gc controllers actually rumble on nintendont? how do i add that setting to my .ini file?

**Comment by ccfman2004** [comment] 2020-08-26 02:00
I couldn't get the PS3 controller to vibrate on the Wii either.

**Comment by revvv** [comment] 2022-02-23 18:01
I had the same problem with my XBOX360 controller... (my fork)

I finally found out that the problem is already fixed with this single line, which was added 9 month ago:
https://github.com/FIX94/Nintendont/blob/5cfb2f17765cf0722865c0a9aba22402bf182283/loader/source/ppc/PADReadGC/source/PADReadGC.c#L215

Thank you so much!
Didn't update my fork for quite some time, but yesterday I moved to my Wii U and this feature didn't work.
It took me a lot of debugging...

**Closed** 2022-02-23 19:00 UTC

**Comment by carnage702** [comment] 2022-02-23 19:03
> I had the same problem with my XBOX360 controller... (my fork)
> 
> I finally found out that the problem is already fixed with this single line, which was added 9 month ago:
> 
> https://github.com/FIX94/Nintendont/blob/5cfb2f17765cf0722865c0a9aba22402bf182283/loader/source/ppc/PADReadGC/source/PADReadGC.c#L215
> 
> Thank you so much! Didn't update my fork for quite some time, but yesterday I moved to my Wii U and this feature didn't work. It took me a lot of debugging...

just a question since you did the rumbling code for xbox360 fork,  any chance you explain me how to get those rumble values? i wanted to give rumble to dualshock 4  and i cant figure out how fix94 got those rumbles values on the inis, any hints? what program to use or get?

**Comment by revvv** [comment] 2022-02-24 08:30
> just a question since you did the rumbling code for xbox360 fork, any chance you explain me how to get those rumble values? i wanted to give rumble to dualshock 4 and i cant figure out how fix94 got those rumbles values on the inis, any hints? what program to use or get?

Luckily I found an example program, but later I noticed that wireshark is also able to sniff USB messages.

**Comment by carnage702** [comment] 2022-02-24 11:42
> > just a question since you did the rumbling code for xbox360 fork, any chance you explain me how to get those rumble values? i wanted to give rumble to dualshock 4 and i cant figure out how fix94 got those rumbles values on the inis, any hints? what program to use or get?
> 
> Luckily I found an example program, but later I noticed that wireshark is also able to sniff USB messages.

so i got wireshark and have no clue how to analyse the data :S  i wanted to get the info like fix94 got to place on the ini

apareantly you can get something similar to this for rumble to work on the inis

Rumble=1
RumbleType=1
RumbleDataLen=0E
RumbleDataOn=51,00,00,00,FF,00,00,FA,FE,00,00,00,00,00
RumbleDataOff=51,00,00,00,00,00,00,FA,FE,00,00,00,00,00
RumbleTransferLen=07
RumbleTransfers=2

but there is no information on how to find these values or what they mean rumbletype?and so on?

i made a capture on wireshark where i made my dualshock vibrate twice not sure if you can help me out or not.
[ds4.zip](https://github.com/FIX94/Nintendont/files/8132176/ds4.zip)

**Comment by revvv** [comment] 2022-02-24 13:00
I'm sorry, but I don't know either. I was glad to have an example.

You can find out what RumbleType  etc. means by studying HID.c
I guess you knew that already ;-)
