### ISSUE TITLE
hyperkin procube wireless controller for gamecube not working

### ISSUE THREAD

**Issue by zalmox** [FIX94/Nintendont#604] opened 2018-08-02 06:25 UTC
Hi, there is an issue where the official wiiu pro controller works perfectly once it has been pared with the wiiu and a key is pressed after nintendont loads but when the same is tried with the hyperkin procube controller, the controller is disconnected imediatelly. It does work correctly in wiiu mode.
This controller is an almost perfect replica of the original gamecube controller. Hopefully the sync issue will be fixed

**Comment by GB-CG** [comment] 2018-08-02 10:09
Duplicate of #199.

**Closed** 2020-04-06 09:58 UTC
