### ISSUE TITLE
Black screen after launching Nintendont forwarder on Wiiu mode

### ISSUE THREAD

**Issue by MattKimura** [FIX94/Nintendont#487] opened 2017-10-07 19:28 UTC
Edit: A workaround has been found, I explained it here: https://github.com/FIX94/Nintendont/issues/487#issuecomment-337285005

I've been having this problem as soon as I've tried the forwarder. When I launch it, it'll boot into vWii and show the wii logo, then just black screen where buttons don't do anything. Yet if I manually boot vWii then exit back to wiiu and run the nintendont forwarder, it'll work just fine until I shut down the console. I can press Home which reboots to the wiiu home menu, and still be able to launch the nintendont forwarder, as long as the system hasn't been shut down.

I've tried many different workarounds and different versions of Nintendont, including the latest version. There's no clear explanation as to why it's having issues booting Nintendont from the forwarder. 
I've even tried different SD cards.

**Update:** I want to confirm further testing. So I installed the Wiisxr and Not64 overclocked injects on the wiiu menu. I ran an overclock app called sign_c2w_patcher which is what overclocks vWii when you launch wiisxr, and surprisingly Wiisxr loaded up just fine and with gamepad support. So I turned off the system, turned it on and loaded up sign_c2w_patcher and ran Nintendont. Of course it black screens. This confirms that Nintendont specifically has problems because other vWii homebrew app injects work just fine on Wiiu. What's odd is that I can still do the button combo to increase/decrease the screen brightness (Start + dpad up and down). Mashing A doesn't do anything and nor do the other buttons do anything.

**Comment by BlazeUchiha420** [comment] 2017-10-12 00:28
I'm having the exact same issues with this and I've literally tried everything I can possibly do and I still get a black screen with every single gamecube game I try to launch. Some people have no problems getting them to work and some people have nothing but problems. I hope there is some simple solution that I'm overlooking but I've been at this for 3 days now and nothing is working.

**Comment by quinho901** [comment] 2017-10-12 18:30
I have exactly the same problem, I've already tried other SD cards and the same happens. I think It can be something with CBHC, since i've seen people who have Coldboot Haxchi and the black screen problem.
I have the latest nintendont boot.dol installed in my /apps/Nintendont/ folder . The only thing that seems to work is entering vWii menu and rebooting to the Wii U menu, then starting the GC game.

**Comment by carnage702** [comment] 2017-10-12 18:31
i use cbhc and have no issues.

**Comment by MattKimura** [comment] 2017-10-12 18:36
@carnage702 I can confirm that this issue is specifically related to Nintendont, because I can launch other vWii homebrew apps such as Wiisxr and not64 from the wiiu menu. Even when I try to launch Nintendont with sign_c2w_patcher (Which is silly), I get a black screen. 

Both Nintendont fowarder and indivisual GC injects result the same. It's completely odd because I can match someone else's setup as much as possible but I can't pinpoint what's different about my system or SD files. With so many different combinations I've tried, I just gave up and simply use the solution instead, which is to launch vWii, exit then launch a GC inject.

**Comment by carnage702** [comment] 2017-10-12 18:42
well my only guess is some hardware issues either sds or the sd slot, or your files get corrupted when passing to the sd card and instal becuase nintendont is much more picky and demands much more from sd and the system than a normal app does.

**Comment by MattKimura** [comment] 2017-10-12 18:47
@carnage702 Hmm the strange part is that I can normally use Nintendont from vWii, and always have been with no problems whatsoever. The Wiiu is having a hard time rebooting to vWii and loading up Nintendont. Perhaps I should try putting the nintendont app files on a USB flash drive and seeing if that offers any better bootup. I've tried three different SD's. Maybe some Wiiu's have different vWii nand chips, Im absolutely sure nothing is corrupted in vWii because everything works in vWii. 

Literally launching vWii, exiting then running Nintendont in wiiu menu shows that my SD card definitely works just fine. This problem only happens with Nintendont.

**Comment by carnage702** [comment] 2017-10-12 18:49
well you cant boot nintendont with that overclock patcher unless you compiled yourself and cou unlocker nintendont fowarder btw.

**Comment by carnage702** [comment] 2017-10-12 18:53
btw just ofr the heck of it take some print screen of your sd card root, then inside the apps folder and then inside the nintendont folder i want to see waht you have there.

**Comment by BlazeUchiha420** [comment] 2017-10-13 20:41
@MattKimura do you have cbhc? I have the exact same problem and I have tried 3 different sd cards also and have also copied other people's sd configs and tried every version/forwarder I could find. I've been at this literally all week so I would be happy if exiting the wii menu to wii u mode works. My wii u reboots when I exit vWii mode though so I don't know if it works. Only my first sd was corrupted my last 2 are pretty much brand new and all my apps work perfectly except this one.

**Comment by MattKimura** [comment] 2017-10-13 21:53
@BlazeUchiha420 It seems like a select amount of users have this issue and there's no clear way to figure out why it's happening. I do have another idea to try though, can you try it for me. Get a FAT32 USB flash drive and put the Nintendont files on it. Then try booting the forwarder to see if it still black screens. Let me know how that goes.

**Comment by BlazeUchiha420** [comment] 2017-10-13 22:45
Alright I'll give it a shot and let you know what I find

**Comment by BlazeUchiha420** [comment] 2017-10-13 22:52
you mean wii u vc right?

**Comment by BlazeUchiha420** [comment] 2017-10-13 23:24
nope wouldn't load from usb. Going into Wii mode didn't work for injections either but Nintendont boots just fine for me. I just can't play games off my sd card. I wonder if it's because of kind of sd card I'm using. Sandisk Ultra 64gb sdxc. I've heard that they're not as compatible as other sd cards. Both my sd and micro sd are Sandisk Ultra

**Comment by BlazeUchiha420** [comment] 2017-10-14 16:45
@MattKimura got it working! If you have the gamecube bios on the root of your sd card, get rid of it! I also used the fw.img this time too, but it also appears to work just fine without it.

**Comment by BlazeUchiha420** [comment] 2017-10-14 18:22
also holding holding the A button when it boots into Wii Mode briefly takes you into Nintendont to boot up the virtual memory card if you have the setting on. This also seems to help a little bit.

**Comment by carnage702** [comment] 2017-10-14 21:32
it seems you had a corrupt bios file then wich makes sence why no game started since if you have a bios nintendont will first play the bios and then the game.

**Comment by BlazeUchiha420** [comment] 2017-10-15 00:03
is it still possible to use one then? If so, does it go on the root?

**Comment by carnage702** [comment] 2017-10-15 07:51
yes put it on the root of the sd card named iplusa.bin or ipljap.bin the pal bios does not work on vwii or wiivc inject.

**Comment by Cha0sC0re** [comment] 2017-10-15 11:14
I got rid of the black screen after launching the game by doing the following steps; deleting the "nincfg.bin" in the root of the SD, not sure why but my GCVC injects didn't want to load, then going through vwii and running nintendont loader to update by pressing 1. I'm using haxchi, with the config command "default=sysmenu" and I got the Nintendont loader v5.471 and go about 10 games in the SD card working and the GameCube VC injects from WiiU USB Helper of Mario Sunshine and MKDD to work. But I still can't get Pokemon XD to load though, I keep getting the black screen of death. lol

**Comment by carnage702** [comment] 2017-10-15 12:41
some games are not compatible with certain settings, make sure your not focing anything the games doesnt like and that you have a good iso.

**Comment by BlazeUchiha420** [comment] 2017-10-15 16:50
@carnage702 what are the optimal settings then for future reference?

**Comment by carnage702** [comment] 2017-10-15 17:21
the settings for perfect compat is everything off  except mc emu wich can be on

wiiu widescreen can also be on or off doesnt affect compat since it just makes the games 4:3 or stretched 4:3

every other setting like force widescree(true 16:9) ,width,foce videomodes,progressive, unlock read speeds, logs and all that stuff can break games, depending how picky they are.

**Comment by YellowHoneyBear** [comment] 2017-10-16 01:36
I was having the same issue as everyone else. 

Black screen sometimes after Wii logo comes on GC injects and on Nintendont forwarder i would get sometimes a black screen with the number 3. But i would still be able to select things and start a game. 

I then proceeded to do the steps as stated above. By Deleting  the "nincfg.bin"  file and updating Nintedont everything seems to work fine for now. But i wouldn't be surprised if it stopped working, since before when i would change something, it would seem it would work at first with no black screen and the black screen issues start to pop up again a bit later. 

I will report back it has issues again.

**Comment by jgomeziii** [comment] 2017-10-17 16:17
Hello can someone help me please?? I get the black screen of death. I have turn mario party 4 iso into a gcm or iso nothing works. Plus i don't know if it matters if i have my vwii mode hack too? I tried all you guys suggestions and i have failed to get this game working.

**Comment by MattKimura** [comment] 2017-10-17 23:29
@carnage702 @BlazeUchiha420 @YellowHoneyBear @Cha0sC0re @quinho901 @jgomeziii 
There's now a solution to this black screen issue with Nintendont! This is thanks to the Wii VC inject of Homebrew Channel. You first have to install FIX94's Homebrew Channel 1.1.4 in vWii, which installs as a separate HBC from your original. Now install the HBC Wii VC inject on the wiiu side (With CFW enabled) and launch it. It will reboot to vWii and boot up Homebrew Channel, but it has gamepad support. Now launch Nintendont and it will literally work like normal, with gamepad support. 
It seems that booting HBC first gives you that vWii boot you needed to make nintendont work. Remember on my original post how I said that booting vWii first, exiting to wiiu and running nintendont made it work. This relates to that.

Downloads:

[Wii VC inject of HBC](https://drive.google.com/drive/folders/0BzEB8f_rxW-oSzFRaXJEalFQZUE)  Install with CFW enabled with Wup installer

[Homebrew Channel 1.1.4 by Fix94](https://github.com/FIX94/hbc/releases) Install with a wad manager such as YAWMM


It seems like Fix94 unintentionally created a workaround to our unique problem. You still can't boot Gamecube injects as expected, but you can still essentially boot Nintendont and play with the gamepad just as you wanted to. The day has finally come when we can play Nitnendont with the gamepad, now there's a workaround that works just good as launching the nintendont wiiu forwarder.

**Comment by carnage702** [comment] 2017-10-18 06:00
it doesnt matter what hbc you have installed on vwii at all, wiivc doesnt care what you have on vwii.

**Comment by jgomeziii** [comment] 2017-10-18 06:36
So what worked for me was delete my nintendont then reinstall everything! Looks like i had corrupt files or somesort.

**Comment by jgomeziii** [comment] 2017-10-18 06:39
Plus my games from psx loading from the channel on the wii u. Where giving the black screen too. All i needed for that is to update from vwii the core. It fix itself!

**Comment by quinho901** [comment] 2017-10-18 10:46
@MattKimura I'll try it later then i report back if it worked.

**Comment by MattKimura** [comment] 2017-10-18 21:20
@carnage702 It did matter what HBC I have installed, because I installed the HBC inject on the wiiu side and I launched it. It just resulted in a dsi exception error. So Im like hmm I must really need to install FIX94's HBC with it's unique game ID. If this doesn't exist, you cannot launch HBC from the inject. The inject looks for a specific game ID installed in vWii and I know this because it was made using FIX94's Wii VC channel booter which you can enter an ID into a txt file. As soon as I installed FIX94's HBC 1.1.4, the inject then worked as expected. And from there, Nintendont was launchable.

**Comment by carnage702** [comment] 2017-10-18 21:44
what i meant is wiivc inject doesnt search or look for anything installed on vwi

inject is not vwii and they dont cross check at all.

**Comment by MattKimura** [comment] 2017-10-18 21:47
@carnage702 ah I get what you're saying, so the Wii game/gamecube game/Homebrew app you inject, lies within the inject and the system reboots to vWii to make use of it. And doesn't look for any installeed channels. Makes me wonder why I got a Dsi exception error before then.

**Comment by carnage702** [comment] 2017-10-18 21:55
vwii and wiivc inject are too seperated systems , vwii runs on os0 and wiivc runs on os1 so its like you have two well 3 with wiiu mode OSs using the same cpu and such so whatever you have isntalled on vwii, cios,games or whatever makes no diference to os1, since os1 has its own ios and codding so yeah think of them as  separated systems only sharing the save folder to save games thats about it, you probably got a bad install or something.

**Comment by MattKimura** [comment] 2017-10-18 22:00
@carnage702 Thanks for the explanation, I never knew about that. Now I can get a better visualization of what I'm booting into when I boot up WiiVC. I'll edit the post above. perhaps I had bad luck or I needed a fresh boot to get proper performance. I still wonder why booting vWii, exiting then running WiiVC allows Nintendont to work all of a sudden from the wiiu side until I shut down the system.

**Comment by carnage702** [comment] 2017-10-18 22:04
probably have some issue l that doesnt initialize the sd card correctly or something so your sd card was never initialized to being with on wiivc inject, the old fowarders had issues with stuff installed on usb rather than nad and such.

**Comment by YellowHoneyBear** [comment] 2017-10-19 23:20
Qeuestion, how is everyone here accessing CFW? Mocha? Or Haxchi's built in CFW? Or IOSU Hax?

**Comment by YellowHoneyBear** [comment] 2017-10-19 23:33
Comparing My Wii U which did have the black screen problem to his which he claimed he didn't, the only different was how we accessed CFW. I used Mocha and he still used FW.IMG file. Which was IOSUHAX. So going to see if that helps. 

I tried updating Nintendont and doing what other users did and it didn't work.  So i'm going to see if this helps.

**Comment by YellowHoneyBear** [comment] 2017-10-20 00:23
https://mega.nz/#F!J6I0VJhB!tCUBGjZb-Fl9zGp4-O2OsQ

Here's a link to the CFW. Try this with Haxchi or whatever and see if it helps.

**Comment by carnage702** [comment] 2017-10-20 06:03
i just use the cfw buikt in cbhc and most people just use haxchi built in cfw too or mocha and no one has issues afaik, any method is good.

**Comment by YellowHoneyBear** [comment] 2017-10-20 13:37
I know that there is a workaround, but this is still an issue. because this makes us not be able to access Gamecube injects. It's really frustrating. Hopefully @FIX94 develops  a fix for this. Because a enough amount of people are having this issue.  
@carnage702 
What you say is probably true. But who knows it might help, i am using Mocha which no one really uses. I'm just grasping at straws at this point.

**Comment by carnage702** [comment] 2017-10-21 09:14
the problem is we cant fix what we cant replicate.

**Comment by alexLePalois** [comment] 2017-12-12 20:47
I had the same issue, and now it works.
For me, the problem was linked with rednand. Indeed, before, I installed the nintendont forwarder from rednand (with mocha or fw.img app, same effect) on my hdd.
But when I tried to install it with a CFW (mocha) from SYSNAND on my hdd, it worked. Seems logic because the vwii hacked version is on sysnand.

**Closed** 2017-12-23 09:35 UTC

**Comment by MatteKalle** [comment] 2018-01-31 20:09
Hi!
After trying for some days now I finally fixed this. Probably it's not the same solution for you all but maybe it will help someone.
What finally fixed it for me:
I put the SDcard in my computer, under the Saves-folder there was a lot off files and folders with strange symbols. I could not delete, move or do anything. I opened Properties for my SD card and made the choice to "check now..." under Tools tab. Checked "Automatically fix file system errors".
When I looked at the  SD card again the Saves folder was gone. Instead there was a Saves-file which I then deleted. I then created the saves folder again.
Thats all! Now I can start up Gamecube injects =))
I have checked some off my Wii U games and the saves seem to be there and working. Maybe all the strange saves was from when I was using loadiine? I don't know but most importantly everything is 100% ok now =)

**Comment by Mdltd** [comment] 2018-02-16 02:06
I had the same problem with black screen with nintendont games threw wii u vc injecs but i couls launch from vwii the fix was the easyist thing ever i launched vwii went into nintendont settings and changed vidio width to auto now i have black lines on the side of my screen in nintendont loader but they go away when i launch my games with wiiu widescreen on so i can live with the black lines in my loader and full screen games better then full screen loader and all black screen games lol hope this helps some people

**Comment by Mdltd** [comment] 2018-02-16 02:09
Dont mean to double post but putting naming iso files game.iso and putting them in folders with the games name without symbols is important

**Comment by Catarax** [comment] 2019-10-31 02:48
Some solutions :
1) Get Wii U channel version of 2017 build from Wii U USB Helper (type simply Nintendont) (Be sure to set the same settings as your previous version else it'll change settings on the original one)

2) HBCvWii channel (Wii U) https://drive.google.com/drive/folders/0BzEB8f_rxW-oSzFRaXJEalFQZUE
2.1) Update Homebrew Channel vWii to v1.1.4-1 (https://github.com/FIX94/hbc/releases) using Another Wad Manager Mod to get GamePad support on Homebrew Channel (you can use L/R/A/B)

**Comment by Zengobag** [comment] 2021-03-19 19:01
Right.. I've had my Wii U for roughly 2 months.. I use Haxchi and Nintendont forwarder with NO problems - even running with a Gamecube controller with the official adapter.. You are all looking at the wrong things..  I'll upload my forwarder and install as usual.. It works as it should.

**Comment by Zengobag** [comment] 2021-03-19 19:17
Oh.. Bought the Wii U solely for Gamecube games but have other games installed now.. You just need the right program but I can't post it as it links directly to Nintendo eShop. I can post a link to a video tho. ;) can't I?
https://www.youtube.com/watch?v=WDymS9HNS9w&t=44s

Look below for failed shack..

**Comment by Zengobag** [comment] 2021-03-19 19:57
****

> Dont mean to double post but putting naming iso files game.iso and putting them in folders with the games name without symbols is important

Not needed now.. They are picked up as seperate files. Not fully tested as I don't have a "short" game with 2 discs to test.. Baten Kaitos is only one I have set like above in a folder and both are listed in full even tho Game.iso and Disc2.iso are filenames.
