### ISSUE TITLE
Switch Pro controller support possible?

### ISSUE THREAD

**Issue by Tschuuuls** [FIX94/Nintendont#618] opened 2018-10-03 20:32 UTC
Hi,
I was just wondering if it's possible/planned to add Switch Pro controller support, as it should be a USB HID device with some proprietary additions mixed in. The initialization looks a bit different than on a normal HID device (https://gbatemp.net/threads/reverse-engineering-the-switch-pro-controller-wired-mode.475226/)
There are linux drivers for it here https://github.com/shinyquagsire23/HID-Joy-Con-Whispering.

Keep up the good work 👍

**Comment by GB-CG** [comment] 2018-10-04 00:06
Duplicate of #480 and #593.

**Comment by Missingphy** [comment] 2019-06-15 20:18
https://gbatemp.net/threads/how-to-use-xbox-one-switch-pro-and-more-controllers-wirelessly-on-nintendont.540706/#post-8676288 wireless support :)

**Closed** 2020-11-14 20:43 UTC
