### ISSUE TITLE
Add compatibility with the Switch Pro Controller

### ISSUE THREAD

**Issue by wshield05** [FIX94/Nintendont#1027] opened 2022-09-03 10:50 UTC

**Comment by GB-CG** [comment] 2022-09-03 13:29
Duplicate of https://github.com/FIX94/Nintendont/issues/480

**Comment by carnage702** [comment] 2022-09-03 13:52
issues is not a request thread, nintendont already supports loads of controllers, if anyone wants more they will have to find someone or do the work themselves.

**Closed by carnage702** 2022-09-03 13:52 UTC
