### ISSUE TITLE
Clock Speed Issue

### ISSUE THREAD

**Issue by Zephiles** [FIX94/Nintendont#336] opened 2016-11-30 07:00 UTC
This is a followup of a closed issue, as there is now proof that it causes issues: https://github.com/FIX94/Nintendont/issues/335

To sum up what the closed issue was about, Nintendont uses a different clock speed than the Wii does when booting via the disc channel, and this causes the in-game timer for Paper Mario: The Thousand-Year Door to not display correctly. It was stated that this would not cause any real issues, but an issue has been found.

As stated in the closed issue, the process of obtaining the Yoshi can result in a different color due to this issue. A video recording of this now exists to prove it. In the video, the file used has saved exactly 4 minutes after obtaining the egg, so it only needs to wait 2 more minutes before the color will change. The first test is done via the disc channel, and waits roughly 2 minutes 15 seconds before allowing the egg to hatch. This results in the Yoshi being red, which is normal. The second test is done via Nintendont, in which the same steps are done, except that the result is a green Yoshi. This is obvious proof that the clock speed difference can in fact cause some issues in the game.

The video can be found here: https://www.twitch.tv/yoshizill/v/104290802

And yes, I am aware that this is done on an older version of Nintendont, but I can confirm that the exact same things still happen on the current release version.

**Comment by MrJPGames** [comment] 2016-11-30 14:50
The issue is not Nintendon't it's the save. You should get to that point in nintendon't and it will have the same exact color as the disc channel does. The issue is created by using MIOS (gamecube mode) saves in nintendont.

Like was said in the previous issue you opened, it's not an issue. And what you showed here is also not an issue it is a difference that is created due to using the same save on both mios and nintendont. You can see this in the video too. The time at which you start is different (5:24 for MIOS and 3:36 for nintendont) if you were to play the game for 5:24 minutes in nintendon't (or hack the save to display 5:24 in nintendont) the result will be the same on both versions.

Please close this issue, and the poster of the issue please stop posting this as an issue.

Thank you.

**Comment by GerbilSoft** [comment] 2016-11-30 15:00
He did say there was something about Yoshi eggs being different color at the same onscreen timer value in Nintendont and MIOS/GameCube, so there might be something there. Regardless, this probably won't be fixed unless someone who's really into TTYD and can reverse-engineer PPC code figures out what needs to be patched.

**Comment by carnage702** [comment] 2016-11-30 18:03
AFAIK is the time the game has been played not the save time.

**Comment by Zephiles** [comment] 2016-11-30 19:47
@MrJPGames the fact that this even happens in the first place is proof enough that this is an issue. There are multiple people that use Nintendont for the sole purpose of using cheats with the game in order to practice things within the game, and this has proven to potentially cause problems. You can't actually expect someone to only use saves specifically for Nintendont and not for the MIOS, and vice versa.

If you truly believe that this isn't an issue, then you are very ignorant.

**Comment by carnage702** [comment] 2016-11-30 20:32
im gonna explain to you what you probably didnt understood.

the save files saves the time as the ticks that went by when playing, then compares the ticks with the processor speed of the console and gives you the actual time.

obviously very few ticks went by when you played on the gc or gc mode, and when that tick value is comparable to the wii processor speed it obvisouly think it passed much less time. there is nothing that can be done.

if you started your entire game on nintendont then the time would have been correct, if it said 4 hours you played it for 4 hours but if you putted that save file on a gc it would compare the ticks from the wii to the gc processor and it would say probably 6 hours becuase much more ticks were saved on the save file and didnt have the wii processor to check them.Remenber nintendont does not emulate the cpu or the GPU we never touch those 2 things.


So there cant be a fix per say, think of it like an adding number.

to make it simple 

imagine the gc adds 2 to the timer for every hours passed by and the gc processor is also 2 lets imagine you played for one hour and saved.

the game would get the save file with 2 ticks  and divide by the console clock speed 2 and you played for one hour wich would be correct.

them lets say the wii adds 3 ticks to the save file for each hour and the wii clock speed is also 3, if you played one hours 3/3 would still give you one hour on the save file wich is correct.

now if you move a gc save wich has a 2 on the save file you would get 2/3 when loading the save file on teh wii,wich would give around 40 minutes instead of the entire hour.

See how this happens? we cant patch saves automaticaly and most games get the processor speed by themselves of the console thats why only like 10 games needed speed patches to get them normal speed. we cant fix what isnt wrong, the math is all correct, you dont play more or less its just becuase of math comparinson of what is on the save file, so the only fix is go to the save file and alter yourself the ticks in there to compensate for the wii or gc  depending on what you want, we cant just write a save patcher becuase them  it would patch nintendont native saves since there is no detection and each save has its own time varaible and whatnot so yeah i hope you understood the entire  thing and why it wont be well "fixed".

**Closed by carnage702** 2016-11-30 20:32 UTC
