### ISSUE TITLE
Star Wars Rogue Squadron III graphics corrupted 

### ISSUE THREAD

**Issue by kscorpionx** [FIX94/Nintendont#967] opened 2022-01-27 04:18 UTC
In the first mission "Revenge of the empire", when starting to play with the x-wing, the graphics under the A button icon show many rainbow lines, instead of the power meter, after the first cutscene it goes back to normal , but then In the second scene, the graphics displayed are corrupted.

**Comment by carnage702** [comment] 2022-01-27 07:01
this is a known issue the life/shield meter randomly gets corrupted and randomly fixes itself, no one found out why tough, so the chances of being fixed are close to zero.

**Comment by GB-CG** [comment] 2022-01-27 10:53
Duplicate of https://github.com/FIX94/Nintendont/issues/352

**Comment by carnage702** [comment] 2022-01-27 12:45
like it said abode its a duplicate issue.

**Closed by carnage702** 2022-01-27 12:45 UTC
