### ISSUE TITLE
BBA Stuff

### ISSUE THREAD

**Issue by fancythedeveloper** [FIX94/Nintendont#601] opened 2018-07-20 22:18 UTC
Is it possible to integrate BBA features. I'm assuming this is gonna require testing in 4 areas:
1. Nintendont & GC LAN
2. Nintendont & Nintendont (2 Wiis) LAN
--------------------------------------------------
(Xlink Kai)
3. Nintendont & GC Online LAN
4. Nintendont & Nintendont (2 Wiis) Online LAN

**Comment by networkfusion** [comment] 2019-01-04 22:50
Duplicate of #144 !

**Closed** 2020-04-06 09:58 UTC
