### ISSUE TITLE
480p quality fixes?

### ISSUE THREAD

**Issue by GerbilSoft** [FIX94/Nintendont#665] opened 2019-04-15 20:16 UTC
It seems the RVL SDK doesn't set up 480p mode properly:
https://www.retrorgb.com/wii-480p-video-bug-discovered.html
https://github.com/ExtremsCorner/libogc-rice/commit/941d687e271fada68c359bbed98bed1fbb454448
https://github.com/ExtremsCorner/libogc-rice/commit/7795d781ff84e64d19ad45a97bfc1dd259bee634

The patch in libogc-rice only applies to Wii games, not GameCube games, but it's possible that Nintendont is affected because it runs in Wii mode.

Overall diff: https://github.com/ExtremsCorner/libogc-rice/compare/15795a3d...7795d781

The main change appears to be calling __VISetOverSampling(3), which is implemented as follows:

```c
static void __VISetOverSampling(u8 mode)
{
	__VIWriteI2CRegister8(0x65, mode);
}
```

According to https://wiibrew.org/wiki/Hardware/AV_Encoder, register 0x65 is "color DAC control (oversampling ?)", and "modifying the default value does [not] seem to have any effect on retail Wii."

NOTE: The example initialization code has hard-coded register values based on dumping data from retail games, and they all appear to have the value 0x08 set for this register.

**Comment by hosaka-corp** [comment] 2019-04-20 18:01
This affects Nintendont when grrlib does video initialization in the loader. Proper solution is probably just to wait for the changes to reach upstream libogc.

**Comment by hurda** [comment] 2019-05-03 11:04
Extrems' PR been sitting in their repo unreplied for three weeks now, and their opinion about his libogc-fork in the past were rather negative.

**Comment by jacobopantoja** [comment] 2019-09-03 16:04
@hosaka-corp So, if I understand it correctly, when Extrem's PR is merged into @devkitPro's `libogc`, simply recompiling `Nintendont` would be enough?

**Comment by wiidev** [comment] 2019-09-05 01:14
We might eventually receive an official update, but for now you can easily patch the existing dol file yourself.

Download and tutorial: https://gbatemp.net/posts/8606161

Extrems confirmed that it should work because GC games don't need to be patched.

**Comment by jacobopantoja** [comment] 2020-01-12 22:13
I've seen that [libogc release 1.8.23] (https://github.com/devkitPro/libogc/releases/tag/v1.8.23) already includes the 480p fix, and was released on 2019-10-02. The file loader.dol received some updates during October. Is any of them supposed to have the 480p fix already? Or should we wait for an "official" release?
Thx

**Comment by hurda** [comment] 2020-02-02 10:01
No, the latest dol (2019-10-08) still uses the old libogc without the video-fix.
You have to hexedit the file, search for "38 80 00 01 38 60 00 65" and replace that section with "38 80 00 03 38 60 00 65". That trick works with other Wii-apps, too.

**Closed** 2020-04-06 10:05 UTC

**Comment by gingerbeardman** [comment] 2020-04-28 12:12
Here's a 480p-fix modified version the latest release (8 Oct 2019) as of this post.

[loader.zip](https://github.com/FIX94/Nintendont/files/4545602/loader.zip)

**Comment by jacobopantoja** [comment] 2021-01-08 18:54
@carnage702 Does the version of commit d1b29b0d08899ca8e2cd4cd7899d9dd2fda281df include this fix? I.e. was it compiled with libogc v1.8.23 or higher?
@gingerbeardman Thanks for the file, it went unnoticed for me until now.

**Comment by carnage702** [comment] 2021-01-08 23:16
> 
> 
> @carnage702 Does the version of commit [d1b29b0](https://github.com/FIX94/Nintendont/commit/d1b29b0d08899ca8e2cd4cd7899d9dd2fda281df) include this fix? I.e. was it compiled with libogc v1.8.23 or higher?
> @gingerbeardman Thanks for the file, it went unnoticed for me until now.

it was compiled with the latest libogc available at that date so i assume it has.

**Comment by philou-felin** [comment] 2022-02-06 14:13
> > @carnage702 Does the version of commit [d1b29b0](https://github.com/FIX94/Nintendont/commit/d1b29b0d08899ca8e2cd4cd7899d9dd2fda281df) include this fix? I.e. was it compiled with libogc v1.8.23 or higher?
> > @gingerbeardman Thanks for the file, it went unnoticed for me until now.
> 
> it was compiled with the latest libogc available at that date so i assume it has.

Hi! I'm a "dumb" end-user. I would like to have a "Yes" or "No" answer.

Does Nintendont automatically applies the fix discovered by Extrems?
